In [1]:
import numpy as np

Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2

In [2]:
arr1 = np.array([5, 10, 15, 20, 25])

# a) Addition of 2 to all elements
add_arr = arr1 + 2

# b) Multiply 3 with all elements
mul_arr = arr1 * 3

# c) Divide every element by 2
div_arr = arr1 / 2

print("Q1 Results:")
print("Addition:", add_arr)
print("Multiplication:", mul_arr)
print("Division:", div_arr)

Q1 Results:
Addition: [ 7 12 17 22 27]
Multiplication: [15 30 45 60 75]
Division: [ 2.5  5.   7.5 10.  12.5]


Q.2 Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])

In [3]:
arr2 = np.array([1, 2, 3, 6, 4, 5])

# a) Reverse the NumPy array
reversed_arr = arr2[::-1]
print("\nQ2 Results:")
print("Reversed Array:", reversed_arr)

# b) Find the most frequent value and its indices
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

most_frequent_x = np.bincount(x).argmax()
indices_x = np.where(x == most_frequent_x)

most_frequent_y = np.bincount(y).argmax()
indices_y = np.where(y == most_frequent_y)

print("Most Frequent in x:", most_frequent_x, "at indices:", indices_x[0])
print("Most Frequent in y:", most_frequent_y, "at indices:", indices_y[0])


Q2 Results:
Reversed Array: [5 4 6 3 2 1]
Most Frequent in x: 1 at indices: [0 5 7 8 9]
Most Frequent in y: 1 at indices: [0 1 2]


Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column

In [4]:
arr3 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

# a) Access 1st row, 2nd column
element_1_2 = arr3[0, 1]

# b) Access 3rd row, 1st column
element_3_1 = arr3[2, 0]

print("\nQ3 Results:")
print("Element at (1st row, 2nd column):", element_1_2)
print("Element at (3rd row, 1st column):", element_3_1)


Q3 Results:
Element at (1st row, 2nd column): 20
Element at (3rd row, 1st column): 70


Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?

In [5]:
name_array = np.linspace(10, 100, 25)

# Print properties of the array
print("\nQ4 Results:")
print("Dimensions:", name_array.ndim)
print("Shape:", name_array.shape)
print("Total Elements:", name_array.size)
print("Data Type:", name_array.dtype)
print("Bytes Consumed:", name_array.nbytes)

# Transpose using reshape
reshaped_array = name_array.reshape(5, 5).T
print("Reshaped Transposed Array:\n", reshaped_array)

# Checking if T attribute works (Yes, it does)
print("Transpose using .T:\n", name_array.reshape(5, 5).T)


Q4 Results:
Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type: float64
Bytes Consumed: 200
Reshaped Transposed Array:
 [[ 10.    28.75  47.5   66.25  85.  ]
 [ 13.75  32.5   51.25  70.    88.75]
 [ 17.5   36.25  55.    73.75  92.5 ]
 [ 21.25  40.    58.75  77.5   96.25]
 [ 25.    43.75  62.5   81.25 100.  ]]
Transpose using .T:
 [[ 10.    28.75  47.5   66.25  85.  ]
 [ 13.75  32.5   51.25  70.    88.75]
 [ 17.5   36.25  55.    73.75  92.5 ]
 [ 21.25  40.    58.75  77.5   96.25]
 [ 25.    43.75  62.5   81.25 100.  ]]


Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.

In [6]:
ucs420_name = np.array([[10, 20, 30, 40], 
                        [50, 60, 70, 80], 
                        [90, 15, 20, 35]])

# Compute statistics
mean_value = np.mean(ucs420_name)
median_value = np.median(ucs420_name)
max_value = np.max(ucs420_name)
min_value = np.min(ucs420_name)
unique_values = np.unique(ucs420_name)

print("\nQ5 Results:")
print("Mean:", mean_value)
print("Median:", median_value)
print("Max:", max_value)
print("Min:", min_value)
print("Unique Elements:", unique_values)

# Reshape and Resize
reshaped_ucs420 = ucs420_name.reshape(4, 3)
resized_ucs420 = ucs420_name[:2, :3]  # Resize to 2x3

print("Reshaped Array (4x3):\n", reshaped_ucs420)
print("Resized Array (2x3):\n", resized_ucs420)


Q5 Results:
Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array (2x3):
 [[10 20 30]
 [50 60 70]]
