In [13]:
import numpy as np

Question 1

In [14]:
a=np.array([1,2,3,4,5])
print(a+2)
print(a*3)
print(a/2)

[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


Question 2

In [15]:
b=np.array([1, 2, 3, 6, 4, 5])
print(b[::-1])
x = np.array([1,2,3,4,5,1,2,1,1,1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])
values, counts = np.unique(x, return_counts=True)
max_count = np.max(counts)
most_frequent_value = values[np.argmax(counts)]
print("most frequent value in x ={most_frequent_value}")
values, counts = np.unique(y, return_counts=True)
max_count = np.max(counts)
most_frequent_value = values[np.argmax(counts)]
print("most frequent value in xy={most_frequent_value}")

[5 4 6 3 2 1]
most frequent value in x ={most_frequent_value}
most frequent value in xy={most_frequent_value}


Question 3

In [16]:
arr3 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Element at (1st row, 2nd column):", arr3[0, 1])
print("Element at (3rd row, 1st column):", arr3[2, 0])

Element at (1st row, 2nd column): 20
Element at (3rd row, 1st column): 70


Question 4

In [17]:
Hemant = np.linspace(10, 100, 25)
print("Generated array:", Hemant)
print("Dimensions:", Hemant.ndim)
print("Shape:", Hemant.shape)
print("Total elements:", Hemant.size)
print("Data type:", Hemant.dtype)
print("Total bytes consumed:", Hemant.nbytes)
reshaped_array = Hemant.reshape(25, 1)
print("Reshaped array:\n", reshaped_array)
print("Using T attribute:\n", Hemant.T)

Generated array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes consumed: 200
Reshaped array:
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Using T attribute:
 [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Question 5

In [18]:
ucs420_Hemant = np.array([[10, 20, 30, 40], [50, 60, 70, 80], [90, 15, 20, 35]])
print("Mean:", np.mean(ucs420_Hemant))
print("Median:", np.median(ucs420_Hemant))
print("Max:", np.max(ucs420_Hemant))
print("Min:", np.min(ucs420_Hemant))
print("Unique elements:", np.unique(ucs420_Hemant))
reshaped_ucs420_Hemant = ucs420_Hemant.reshape(4, 3)
print("Reshaped array:\n", reshaped_ucs420_Hemant)
resized_ucs420_Hemant = ucs420_Hemant[:2, :3]
print("Resized array:\n", resized_ucs420_Hemant)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array:
 [[10 20 30]
 [50 60 70]]
