In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pl


In [3]:
# PART 1

random_seed = 102316092 
np.random.seed(random_seed)

In [4]:
# 2
months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
categories = ["Electronics", "Clothing", "Home & Kitchen", "Sports"]
sales_data = np.random.randint(1000, 5000, size=(12, 4))

In [5]:
# 3
df = pd.DataFrame(sales_data, columns=categories, index=months)
df.index.name = "Month"

In [6]:
# PART 2
# 1
print(df.head())
print(df.describe())


       Electronics  Clothing  Home & Kitchen  Sports
Month                                               
Jan           1482      1030            2525    1990
Feb           3797      3340            1935    1308
Mar           4989      4900            3490    4065
Apr           1679      1668            4703    3105
May           4972      3547            4323    4140
       Electronics     Clothing  Home & Kitchen       Sports
count    12.000000    12.000000       12.000000    12.000000
mean   3157.416667  2672.333333     3578.250000  3041.583333
std    1448.771420  1329.028034     1021.566633  1213.110387
min    1128.000000  1030.000000     1935.000000  1098.000000
25%    1960.250000  1628.000000     2527.250000  2168.500000
50%    3304.000000  2568.000000     4124.000000  3272.500000
75%    4396.000000  3559.250000     4320.000000  4083.750000
max    4989.000000  4900.000000     4703.000000  4698.000000


In [7]:
# 2 
df["Total Sales"] = df.sum(axis=1)
category_totals = df[categories].sum()

In [8]:
# 3
growth_rates = df[categories].pct_change().mean()

# 4
df["Growth Rate"] = df["Total Sales"].pct_change() * 100


In [9]:
# 5
if random_seed % 2 == 0:
    df["Electronics"] *= 0.9  # 10%
else:
    df["Clothing"] *= 0.85  # 15%

# Part III: Visualizations
plt.figure(figsize=(10, 6))
for category in categories:
    plt.plot(df.index, df[category], marker='o', label=category)
plt.xlabel("Month")
plt.ylabel("Sales")
plt.title("Monthly Sales Trends")
plt.legend()
plt.grid(True)
plt.show()

# boxplot
plt.figure(figsize=(8, 5))
plt.boxplot([df[cat] for cat in categories], labels=categories)
plt.title("Sales Distribution by Category")
plt.show()

NameError: name 'plt' is not defined

Q.2 For the array: array = np.array([[1, -2, 3],[-4, 5, -6]])
 i. Find element-wise absolute value
ii. Find the 25th, 50th, and 75th percenƟle of flaƩened array, for each column, for each
row.
iii. Mean, Median and Standard DeviaƟon of flaƩened array, of each column, and
each row 

In [ ]:
array = np.array([[1, -2, 3], [-4, 5, -6]])

# 1
absolute_values = np.abs(array)
print("Element-wise Absolute Values:\n", absolute_values)

Element-wise Absolute Values:
 [[1 2 3]
 [4 5 6]]


In [ ]:
# 2
flattened_percentiles = np.percentile(array, [25, 50, 75])
column_percentiles = np.percentile(array, [25, 50, 75], axis=0)
row_percentiles = np.percentile(array, [25, 50, 75], axis=1)
print("Flattened Percentiles:", flattened_percentiles)
print("Column-wise Percentiles:\n", column_percentiles)
print("Row-wise Percentiles:\n", row_percentiles)

Flattened Percentiles: [-3.5 -0.5  2.5]
Column-wise Percentiles:
 [[-2.75 -0.25 -3.75]
 [-1.5   1.5  -1.5 ]
 [-0.25  3.25  0.75]]
Row-wise Percentiles:
 [[-0.5 -5. ]
 [ 1.  -4. ]
 [ 2.   0.5]]


In [ ]:
# 3
mean_flattened = np.mean(array)
median_flattened = np.median(array)
std_flattened = np.std(array)
mean_columns = np.mean(array, axis=0)
median_columns = np.median(array, axis=0)
std_columns = np.std(array, axis=0)
mean_rows = np.mean(array, axis=1)
median_rows = np.median(array, axis=1)
std_rows = np.std(array, axis=1)

print("Mean (Flattened):", mean_flattened)
print("Median (Flattened):", median_flattened)
print("Standard Deviation (Flattened):", std_flattened)
print("Mean (Columns):", mean_columns)
print("Median (Columns):", median_columns)
print("Standard Deviation (Columns):", std_columns)
print("Mean (Rows):", mean_rows)
print("Median (Rows):", median_rows)
print("Standard Deviation (Rows):", std_rows)


Mean (Flattened): -0.5
Median (Flattened): -0.5
Standard Deviation (Flattened): 3.8622100754188224
Mean (Columns): [-1.5  1.5 -1.5]
Median (Columns): [-1.5  1.5 -1.5]
Standard Deviation (Columns): [2.5 3.5 4.5]
Mean (Rows): [ 0.66666667 -1.66666667]
Median (Rows): [ 1. -4.]
Standard Deviation (Rows): [2.05480467 4.78423336]


Q.3 For the array: a = np.array([-1.8, -1.6, -0.5, 0.5,1.6, 1.8, 3.0]).
i. Find floor, ceiling and truncated value, rounded values

In [ ]:
a = np.array([-1.8, -1.6, -0.5, 0.5, 1.6, 1.8, 3.0])

# 1.
floor_values = np.floor(a)
ceiling_values = np.ceil(a)
truncated_values = np.trunc(a)
rounded_values = np.round(a)

print("Floor Values:", floor_values)
print("Ceiling Values:", ceiling_values)
print("Truncated Values:", truncated_values)
print("Rounded Values:", rounded_values)


Floor Values: [-2. -2. -1.  0.  1.  1.  3.]
Ceiling Values: [-1. -1. -0.  1.  2.  2.  3.]
Truncated Values: [-1. -1. -0.  0.  1.  1.  3.]
Rounded Values: [-2. -2. -0.  0.  2.  2.  3.]


Q.4 WAP to swap two elements in a list in Python Using a Temporary Variable.

In [ ]:
def swap_elements(lst, i, j):
    temp = lst[i]
    lst[i] = lst[j]
    lst[j] = temp
    return lst


my_list = [10, 20, 30, 40, 50]
i, j = 1, 3 
swapped_list = swap_elements(my_list, i, j)
print("List after swapping:", swapped_list)


List after swapping: [10, 40, 30, 20, 50]


Q.5 Write a Python program to swap two elements in a set by converƟng it to a list first.

In [ ]:
def swap_elements_in_set(s, val1, val2):
    lst = list(s)  
    if val1 in lst and val2 in lst:
        i, j = lst.index(val1), lst.index(val2)
        lst[i], lst[j] = lst[j], lst[i]  
        return set(lst)  
    return s 

my_set = {10, 20, 30, 40, 50}
val1, val2 = 20, 40
swapped_set = swap_elements_in_set(my_set, val1, val2)
print("Set after swapping:", swapped_set)

Set after swapping: {40, 10, 50, 20, 30}
